server:
  port: 8081
  shutdown: graceful

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: okj-redis-headless.okj-exchange-env-base.svc.cluster.local

logging:
  file:
    path: target/logs
