spring:
  application:
    name: kokona
  docker:
    compose:
      enabled: false

logging:
  config: classpath:logback-spring.xml
  charset:
    file: UTF-8
    console: UTF-8
  level:
    root: info
